# Mathematics for Machine Learning Pre-Class assignment 3 Matrix Scratch
## Name: Nguyen Anh Hoang Phuc

## Problem 1

In [37]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

Result is:
$
[[ 6,  29, -20], \\
[ 12,  52,  38], \\
[-18, -51, -48]] \\
$
Let denote result is R 
At position $R[i,j]$, I get row i of matrix A inner product with column j of matrix
$R[0,0] = A[0,0]*B[0,0] + A[0,1]*B[1,0] + A[0,2]*B[2,0] = -1*0+2*0+3*2 = 6$
$R[0,1] = A[0,0]*B[0,1] + A[0,1]*B[1,1] + A[0,2]*B[2,1] = -1*2+2*2+3*9 = 29$
Similar with other positions of matrix R

## Problem 2

In [38]:
result = []
for row in range(a_ndarray.shape[0]):
    row_val = []
    for col in range(b_ndarray.shape[1]):
        temp = a_ndarray[row,:]*b_ndarray[:,col].T 
        row_val.append(temp.sum())
    result.append(row_val)
result = np.array(result)
print("Calculation process performed by hand calculation from scratch implementation using NumPy: \n {}".format(result))

Calculation process performed by hand calculation from scratch implementation using NumPy: 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## Problem 3

In [39]:
code = a_ndarray[0,:]*b_ndarray[:,0].T
code = code.sum()
print("Without using np.matmul() , np.dot() or @ operators, result is {}".format(code))

Without using np.matmul() , np.dot() or @ operators, result is 6


## Problem 4

In [42]:
def matrix_product(A, B):
    result = []
    for row in range(a_ndarray.shape[0]):
        row_val = []
        for col in range(b_ndarray.shape[1]):
            temp = a_ndarray[row,:]*b_ndarray[:,col].T 
            row_val.append(temp.sum())
        result.append(row_val)
    result = np.array(result)
    return result

In [44]:
mat_mul = matrix_product(a_ndarray, b_ndarray)
print("Write function that takes matrices A and B as arguments and returns the matrix product, result is \n {}".format(mat_mul))

Write function that takes matrices A and B as arguments and returns the matrix product, result is 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## Problem 5

In [53]:
def matrix_product_cond(A, B):
    if A.shape[1] != B.shape[0]:
        print("The input is invalid, the number of columns of left matrix is not equal to the number of rows of right matrix")
        return None
    result = []
    for row in range(a_ndarray.shape[0]):
        row_val = []
        for col in range(b_ndarray.shape[1]):
            temp = a_ndarray[row,:]*b_ndarray[:,col].T 
            row_val.append(temp.sum())
        result.append(row_val)
    result = np.array(result)
    return result

In [54]:
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
mat_mul_wrong = matrix_product_cond(d_ndarray_,e_ndarray)

The input is invalid, the number of columns of left matrix is not equal to the number of rows of right matrix


## Problem 6

In [56]:
a_ndarray_T = a_ndarray.T 
mat_mul_T = a_ndarray_T@b_ndarray
print("Calculate the matrix product that tranpose a array, result is {}".format(mat_mul_T))

Calculate the matrix product that tranpose a array, result is [[ 14  69 -40]
 [ 16  66  34]
 [-18 -63 -36]]
